name: Node.js CI

on:
  push:
    branches: [ main, feature/payfast-samples ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
      continue-on-error: true
    - name: Run lint (if any)
      run: |
        echo "No linter configured; add tests/lint as needed"
